LOAD DATA
INFILE '$MYPROJECTHOME/projetMBDS/SQLLOADER/Client.csv'
INSERT INTO TABLE client
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
AGE,
SEXE,
TAUX,
SITUATIONFAMILIALE,
NBENFANTSACHARGE,
XVOITURE
)
