LOAD DATA
INFILE '$MYPROJECTHOME/projetMBDS/SQLLOADER/Clients_6.csv'
INSERT INTO TABLE client
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
AGE,
SEXE,
TAUX,
SITUATIONFAMILIALE,
NBENFANTSACHARGE,
XVOITURE,
IMMATRICULATION
)
